export { heartbeat } from './heartbeat'
export { weather } from './weather'
export { music } from './music'
export { quote } from './quote'
export { xkcd } from './xkcd'
export { news } from './news'
export { colors } from './colors'
